<?php

/*
// Gebruiker Centraal - inclusie.acf-definitions.php
// ----------------------------------------------------------------------------------
// ACF definities voor inclusie plugin
// ----------------------------------------------------------------------------------
// @package   ictu-gc-posttypes-inclusie
// @author    Paul van Buuren
// @license   GPL-2.0+
// @version   0.0.10
// @desc.     CPT procestips toegevoegd. Mogelijkheid OD-tips toe te voegen op stap-pagina.
// @link      https://github.com/ICTU/Gebruiker-Centraal---Inclusie---custom-post-types-taxonomies
 */

if( ! function_exists('ictu_gc_inclusie_initialize_acf_fields') ) {

	//------------------------------------------------------------------------------------------------
	// velden voor home template
	acf_add_local_field_group(array(
		'key' => 'group_5c90e063ca578',
		'title' => 'Homepage template: inleiding, stappen en doelgroepen',
		'fields' => array(
			array(
				'key' => 'field_5c90fd5fe0a58',
				'label' => 'Inleiding op homepage',
				'name' => 'home_template_inleiding',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5c90e0739fa4b',
				'label' => 'Stappen',
				'name' => 'home_template_stappen',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'stap',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'object',
			),
			array(
				'key' => 'field_5c90e096cca0a',
				'label' => 'Doelgroepen',
				'name' => 'home_template_doelgroepen',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5c9104bff7ade',
						'label' => 'Kies doelgroep',
						'name' => 'home_template_doelgroepen_doelgroep',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'doelgroep',
						),
						'taxonomy' => '',
						'allow_null' => 1,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
					array(
						'key' => 'field_5c910507f7adf',
						'label' => 'Kies citaat',
						'name' => 'home_template_doelgroepen_citaat',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'citaat',
						),
						'taxonomy' => '',
						'allow_null' => 1,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
				),
			),
			array(
				'key' => 'field_5ccfec39e2de3',
				'label' => 'home_template_poster',
				'name' => 'home_template_poster',
				'type' => 'file',
				'instructions' => 'Upload de PDF voor de poster',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5ccfeccee8a61',
				'label' => 'home_template_poster_linktekst',
				'name' => 'home_template_poster_linktekst',
				'type' => 'text',
				'instructions' => 'Dit is de tekst op de downloadknop als je een PDF met de poster hebt toegevoegd.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Download de poster',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'home-inclusie.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	//------------------------------------------------------------------------------------------------
	// velden voor stap
	acf_add_local_field_group(array(
		'key' => 'group_5c8fde441c0a9',
		'title' => 'Stap: inleiding en methodes',
		'fields' => array(
			array(
				'key' => 'field_5c91fb7281870',
				'label' => 'Verkorte titel',
				'name' => 'stap_verkorte_titel',
				'type' => 'text',
				'instructions' => 'Deze tekst wordt als label getoond in het stappenschema. Gebruik bij voorkeur 1 woord.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5cdb1d4374d09',
				'label' => 'Icoontje',
				'name' => 'stap_icon',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'identificeer' => '<img src="/wp-content/plugins/ictu-gc-posttypes-inclusie/images/identificeer.png"> Bereid voor',
					'verdiep' => '<img src="/wp-content/plugins/ictu-gc-posttypes-inclusie/images/verdiep.png"> Ontwerp',
					'ontwerp' => '<img src="/wp-content/plugins/ictu-gc-posttypes-inclusie/images/ontwerp.png"> Test',
					'evalueer' => '<img src="/wp-content/plugins/ictu-gc-posttypes-inclusie/images/evalueer.png"> Evalueer',
					'deel' => '<img src="/wp-content/plugins/ictu-gc-posttypes-inclusie/images/deel.png"> Deel',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'identificeer',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5c90bae01c857',
				'label' => 'Inleiding',
				'name' => 'stap_inleiding',
				'type' => 'wysiwyg',
				'instructions' => 'korte inleiding bij deze stap. Wordt getoond in het cirkelschema op de homepage.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5d7245be8ffc0',
				'label' => 'Titel bij de methodes',
				'name' => 'stap_methodes_titel',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Methodes',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ce3d0e2f8917',
				'label' => 'Inleiding bij de methodes',
				'name' => 'stap_methode_inleiding',
				'type' => 'wysiwyg',
				'instructions' => 'Korte inleiding bij methoden.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Dit is een selectie van methoden, technieken en instrumenten die je in kunt zetten bij het uitvoeren van deze stap. Soms gaat het om standaardmethoden die worden ingezet voor het uitvoeren van een ontwerptraject waarbij de gebruiker centraal staat. Andere methoden richten zich specifiek op inclusie.',
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5c8fde5259d46',
				'label' => 'Methodes',
				'name' => 'stap_methodes',
				'type' => 'relationship',
				'instructions' => 'Kies de bij deze stap horende methodes.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'methode',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'object',
			),
			array(
				'key' => 'field_5d84d94b05b52',
				'label' => 'Procestips titel',
				'name' => 'stap_procestips_sectiontitle',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Procestips',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5d84dcb9d1473',
				'label' => 'Bijbehorende procestips',
				'name' => 'stap_procestips',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'procestip',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'object',
			),
			array(
				'key' => 'field_5d84d4b652e0e',
				'label' => 'Tips Optimaal Digitaal',
				'name' => 'stap_tips_optimaal_digitaal_sectiontitle',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Optimaal Digitaal tips',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5d84d3eed46b2',
				'label' => 'Bijbehorende tips Optimaal Digitaal',
				'name' => 'stap_tips_optimaal_digitaal',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5d84d439d46b4',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Nieuw tip toevoegen',
				'sub_fields' => array(
					array(
						'key' => 'field_5d84d439d46b4',
						'label' => 'Titel',
						'name' => 'stap_tip_optimaal_digitaal_titel',
						'type' => 'text',
						'instructions' => 'De titel van de Optimaal Digitaal-tip',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d84d468d46b5',
						'label' => 'Tip-nummer',
						'name' => 'stap_tip_optimaal_digitaal_tipnummer',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d84d423d46b3',
						'label' => 'URL',
						'name' => 'stap_tip_optimaal_digitaal_url',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5d84d472d46b6',
						'label' => 'Tip-thema',
						'name' => 'stap_tip_optimaal_digitaal_tipthema',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'commitment' => 'Commitment',
							'gebruiksgemak' => 'Gebruiksgemak',
							'informatieveiligheid' => 'Informatieveiligheid',
							'kanaalsturing' => 'Kanaalsturing',
							'procesaanpak' => 'Procesaanpak',
							'samenwerking' => 'Samenwerking',
							'inclusie' => 'Inclusie',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'inclusie',
						'layout' => 'vertical',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => ICTU_GC_CPT_STAP,
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));



}	
